### ISSUE TITLE
Consider releasing binaries

### ISSUE THREAD

**Issue by coxackie** [Windscribe/desktop-v2#10]
Could you please provide binaries (stating what dependencies these may have)? Not everyone can build this, and to be honest using things like Python 2, which is deprecated, does not make it easier...

**Comment by bernerdad** [comment]
Hi.  In the short term, binaries are available from the Windscribe website.  We will be providing binaries, both production and beta, here asap.  The Python 2 dependency is on the board to be replaced with Python 3.  Cheers!

**Comment by yegors** [comment]
The releases section is now live: https://github.com/Windscribe/desktop-v2/releases
