### ISSUE TITLE
[Arch] AttributeError: module 'messages' has no attribute 'Verbose'

### ISSUE THREAD

**Issue by ExperiBass** [Windscribe/desktop-v2#16]
I'm attempting to compile on Arch and i get this error with python:

```
Traceback (most recent call last):
  File "/home/gingka/Builds/Windscribe-desktop/tools/deps/./install_openssl.py", line 117, in <module>
    current_os = utl.GetCurrentOS()
  File "/home/gingka/Builds/Windscribe-desktop/tools/base/utils.py", line 27, in GetCurrentOS
    msg.Verbose("Detected OS: \"{}\"".format(_OS_CURRENT_NAME))
AttributeError: module 'messages' has no attribute 'Verbose'
```
This was after installing `messages`, as its not in the requirements.txt.

System info:
Kernel: 5.14.13-1mbp-16.1-linux-wifi
Python version: `3.10.1`

**Comment by bernerdad** [comment]
Hi.  You'll need to run the install and build scripts using Python 2.  We have it on our roadmap to update the scripts to support Python 3 this year.

**Comment by ExperiBass** [comment]
Ok, so it appears that this is a double issue, as on top of the app only using python2, arch doesnt have pip2 anymore (`pip` is just a link to `pip3`). I'll close this.
