### ISSUE TITLE
Linux (Ubuntu) : No Internet Connectivity

### ISSUE THREAD

**Issue by koplo199** [Windscribe/desktop-v2#2]
Hi,
I compiled the application on Linux (Ubuntu 21.10), and it looks like there's an issue when logging in : 
![Screenshot from 2021-11-12 12-21-20](https://user-images.githubusercontent.com/85577251/141460281-99c3765c-706f-418e-b4ec-2d482cbfcbc0.png)

I did not find any useful information in the logs, any idea where the issue could come from ? (My network isn't proxified, restricted or firewalled, and other applications have no trouble connecting to internet)

[logs.txt](https://github.com/Windscribe/desktop-v2/files/7527263/log.txt)

**Comment by bernerdad** [comment]
Hi.  To work around this issue, please install the route utility via 'sudo apt install net-tools'.  Reliance on the 'route' utility will be removed in our next code release.  Cheers!

**Comment by koplo199** [comment]
@bernerdad It resolved the issue, thank you :)
