### ISSUE TITLE
Windscribe preventing Internet access - Latest Update 2.3.16 or whatever

### ISSUE THREAD

**Issue by KITKATKILLER67** [Windscribe/desktop-v2#20]
Yesterday, I updated my Windscribe to 3.1.6. Then, when I got home, I could not access the internet. When I uninstalled Windscribe, I magically had internet again. I don't know what is going on here but unless you know the problem I'm going to switch to Nord for the times being. Sorry, I did refer three friends to you guys though! Love you still!

**Comment by yegors** [comment]
Guinea Pig channel is for potentially unstable alpha versions of the software meant for testing and technical feedback.  As you provided no additional details, like debug logs, this issue is not actable. 

You should contact support about these matters.

**Comment by KITKATKILLER67** [comment]
oh, ok. sorry

just wanted to alert you about this possible issue.

**Comment by KITKATKILLER67** [comment]
just a bug alert.
