### ISSUE TITLE
Error when running install_qt

### ISSUE THREAD

**Issue by topik0** [Windscribe/desktop-v2#3]
I'm getting an error when running install_qt.  I'm on an Arch system, I have all the dependencies installed as per the documentation.  I am using Python 2.7.18 and I can't find any exact reason why the build is failing.  Everything else builds fine.  I attached a text file containing the output of install_qt.  Let me know if there's any other logs that can help resolve this.  Thanks!
[output.txt](https://github.com/Windscribe/desktop-v2/files/7534681/output.txt)

**Comment by koplo199** [comment]
@topik0 Have you had a look at #1 ? The first commit resolve this exact issue.

**Comment by topik0** [comment]
@koplo199 That seems to have fixed it, thanks!
