### ISSUE TITLE
Error when creating the Debian package

### ISSUE THREAD

**Issue by lilithium-hydride** [Windscribe/desktop-v2#5]
When running `./build_all --no-sign`, it gets through most of it before spitting out a few errors and failing:
```
INFO: Copying wstunnel...
windscribewstunnel
INFO: Copying license files...
open_source_licenses.txt
INFO: Creating Debian package...
dpkg-deb: error: maintainer script 'preinst' has bad permissions 664 (must be >=0555 and <=0775)
ERROR: Command failed: "['fakeroot', 'dpkg-deb', '--build', '/home/builduser/src/desktop-v2/temp/installer/InstallerFiles/../windscribe_2.3.11_beta_amd64']"
All done: 3 minutes 42 seconds elapsed
```
I'm doing this in a fresh `ubuntu` Docker image with [this increasingly-messy script](https://gist.github.com/lilithium-hydride/84b916ea9dece94e3458595fc4573077) that I created as per the README. I was originally doing all of this as root and assumed it to be the source of the errors, so I changed the script to run the build process as a normal user, but this didn't change anything.

**Comment by bernerdad** [comment]
Hi. You can fix this error by ensuring the following files have "Allow executing file as program" permission:
- installer/linux/debian_package/DEBIAN/postinst
- installer/linux/debian_package/DEBIAN/preinst
- installer/linux/debian_package/DEBIAN/prerm

**Comment by lilithium-hydride** [comment]
That worked, thank you!

**Comment by bernerdad** [comment]
Many thanks to @koplo199 for finding this issue, and the fix, for us.
