### ISSUE TITLE
OpenVPN --up script failure

### ISSUE THREAD

**Issue by booYah187** [Windscribe/desktop-v2#6]
Built for linux, Ubuntu 21.04,and am unable to connect.   log shows the below  message, unsure how to proceed. The update-resolv-conf.sh is executable, not sure what other permissions would have an effect. Windscribe-cli connects without issue.

E [011221 04:10:07:015     45.932] [connection]	 OpenVPN version: "2.5.4"
E [011221 04:10:07:015     45.932] [default]	 "cd '%HOMELOCATION%/.local/share/Windscribe/Windscribe2' && /usr/local/windscribe//windscribeopenvpn --config \"%HOMELOCATION%/.local/share/Windscribe/Windscribe2/config.ovpn\" --management 127.0.0.1 33099 --management-query-passwords --management-hold"
E [011221 04:10:07:015     45.933] [connection]	 openvpn process runned:  33099
E [011221 04:10:07:019     45.936] [connection]	 openvpn process finished before connected to openvpn socket
E [011221 04:10:07:019     45.936] [connection]	 answer from openvpn process, answer = "2021-11-30 23:10:07 Note: Treating option '--ncp-ciphers' as  '--data-ciphers' (renamed in OpenVPN 2.5).\nOptions error: --up script fails with '/etc/windscribe/update-resolv-conf': Permission denied (errno=13)\nOptions error: Please correct this error.\nUse --help for more information.\n"

**Comment by bernerdad** [comment]
Hi.  Do the permissions and ownership of update-resolv-conf look like the following?
-rwxrwxr-x 1 root root

**Comment by booYah187** [comment]
It did not, was not set to executable. Was aware the .sh needed it, did not realize the file did, but that seems to have fixed it. Much appreciated.
