### ISSUE TITLE
WStunnel not working on Linux

### ISSUE THREAD

**Issue by kochinc** [Windscribe/desktop-v2#7]
I successfully compiled and installed the app on Linux Mint 20.2. Manually I set connection protocol to each available ones (UDP, TCP, Stealth, WStunnel, and WireGuard) and tested, They all worked except WStunnel.

There was this error message in the log file:
`[wstunnel]	 wstunnel process error: "execvp: Permission denied"`
Looked into /usr/local/windscribe folder, and I found windscribewstunnel was not set executable. After I did `chmod +x /usr/local/windscribe/windscribewstunnel`, WStunnel protocol also works now.

By the way, IKEv2 isn't available at all. Is it not supported on Linux?

**Comment by bernerdad** [comment]
Hi.  Glad to hear you have all the supported protocols up-and-running on Mint!  Correct, IKEv2 is not currently supported on Linux.  It is on our roadmap to implement it.  Our next push to this repo will hide IKEv2 from the UI on Linux.  Have an excellent weekend!

**Comment by kochinc** [comment]
v2.3.15 has the executable set on scripts and programs correctly.

**Comment by djnotes** [comment]
Same problem with WSTunnel on Fedora 37. Only WSTunnel can establish a connection (in UI), but not a single page can be opened. Error is "Server Not Found" in the browser.

![image](https://user-images.githubusercontent.com/9320387/205520141-e1197136-59a7-4475-acc5-ec0122ab0adb.png)
